In [1]:
import pandas as pd

In [44]:
shdi = pd.read_csv('SHDI-SGDI-Total 7.0.csv')

/var/folders/9s/5vl8qm5n629_ld9lvn25vm2c0000gn/T/ipykernel_82008/662316380.py:1: DtypeWarning: Columns (11,14,17,20,23,26,29,32) have mixed types. Specify dtype option on import or set low_memory=False.
  shdi = pd.read_csv('SHDI-SGDI-Total 7.0.csv')

In [45]:
shdi.columns

Index(['iso_code', 'country', 'year', 'GDLCODE', 'level', 'region',
       'continent', 'sgdi', 'shdi', 'shdif', 'shdim', 'healthindex',
       'healthindexf', 'healthindexm', 'incindex', 'incindexf', 'incindexm',
       'edindex', 'edindexf', 'edindexm', 'esch', 'eschf', 'eschm', 'msch',
       'mschf', 'mschm', 'lifexp', 'lifexpf', 'lifexpm', 'gnic', 'gnicf',
       'gnicm', 'lgnic', 'lgnicf', 'lgnicm', 'pop'],
      dtype='object')

In [46]:
shdi

,iso_code,country,year,GDLCODE,level,region,continent,sgdi,shdi,shdif,...,lifexp,lifexpf,lifexpm,gnic,gnicf,gnicm,lgnic,lgnicf,lgnicm,pop
0,AFG,Afghanistan,1990,AFGr101,Subnat,Central (Kabul Wardak Kapisa Logar Parwan Panj...,Asia/Pacific,,.332,,...,46.975,,,3549.393,,,8.175,,,
1,AFG,Afghanistan,1990,AFGr102,Subnat,Central Highlands (Bamyan Daikundi),Asia/Pacific,,.281,,...,44.402,,,2224.831,,,7.707,,,
2,AFG,Afghanistan,1990,AFGr103,Subnat,East (Nangarhar Kunar Laghman Nooristan),Asia/Pacific,,.287,,...,49.445,,,2279.29,,,7.732,,,
3,AFG,Afghanistan,1990,AFGr104,Subnat,North (Samangan Sar-e-Pul Balkh Jawzjan Faryab),Asia/Pacific,,.259,,...,44.385,,,2356.842,,,7.765,,,
4,AFG,Afghanistan,1990,AFGr105,Subnat,North East (Baghlan Takhar Badakhshan Kunduz),Asia/Pacific,,.266,,...,46.269,,,2623.883,,,7.872,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58879,ZWE,Zimbabwe,2021,ZWEr107,Subnat,Midlands,Africa,.958,.59,.577,...,58.544,61.193,55.566,3670.709,3168.011,4233.422,8.208,8.061,8.351,
58880,ZWE,Zimbabwe,2021,ZWEr108,Subnat,Masvingo,Africa,.962,.588,.578,...,62.276,65.641,59.025,3127.485,2706.948,3596.899,8.048,7.904,8.188,
58881,ZWE,Zimbabwe,2021,ZWEr109,Subnat,Harare,Africa,.962,.665,.652,...,60.261,63.25,57.171,7314.452,6235.132,8537.414,8.898,8.738,9.052,
58882,ZWE,Zimbabwe,2021,ZWEr110,Subnat,Bulawayo,Africa,.985,.693,.689,...,62.628,66.056,59.346,9516.362,8073.914,11158.386,9.161,8.996,9.32,
58883,ZWE,Zimbabwe,2021,ZWEt,National,Total,Africa,.961,.593,.58,...,59.253,62.045,56.232,3809.887,3285.934,4396.778,8.245,8.097,8.389,

In [47]:
columns_to_drop = ['iso_code', 'GDLCODE','level','sgdi','shdif','shdim','healthindex','healthindexf','healthindexm','incindex', 'incindexf', 'incindexm','edindexf', 'edindexm','eschf', 'eschm','mschf', 'mschm','lifexpf', 'lifexpm','gnicf','gnicm','lgnic', 'lgnicf', 'lgnicm', 'pop']
shdi.drop(columns=columns_to_drop, inplace=True)

In [50]:
shdi['shdi'] = pd.to_numeric(shdi['shdi'], errors='coerce')
shdi['edindex'] = pd.to_numeric(shdi['edindex'], errors='coerce')
shdi['esch'] = pd.to_numeric(shdi['esch'], errors='coerce')
shdi['msch'] = pd.to_numeric(shdi['msch'], errors='coerce')
shdi['lifexp'] = pd.to_numeric(shdi['lifexp'], errors='coerce')
shdi['gnic'] = pd.to_numeric(shdi['gnic'], errors='coerce')

In [51]:
def categorise_hdi(row):
    shdi_value = row['shdi']
    if (shdi_value >= 0.8):
        return "Very High"
    elif(shdi_value>=0.7):
        return "High"
    elif(shdi_value>=0.550):
        return "Medium"
    else:
        return "Low"
shdi['hdi_category'] = shdi.apply(categorise_hdi, axis=1)

In [94]:
df = shdi[(shdi["country"]=='India') & (shdi['region']=='Total')]
df

,country,year,region,continent,shdi,edindex,esch,msch,lifexp,gnic,hdi_category
24854,India,1990,Total,Asia/Pacific,0.434,0.315,7.996,2.782,58.652,1790.407,Low
24891,India,1991,Total,Asia/Pacific,0.437,0.319,8.027,2.885,59.055,1768.859,Low
24928,India,1992,Total,Asia/Pacific,0.442,0.323,8.057,2.988,59.452,1828.853,Low
24965,India,1993,Total,Asia/Pacific,0.446,0.328,8.088,3.092,59.815,1880.995,Low
25002,India,1994,Total,Asia/Pacific,0.452,0.332,8.119,3.195,60.216,1969.856,Low
25039,India,1995,Total,Asia/Pacific,0.458,0.336,8.150,3.298,60.596,2082.000,Low
25076,India,1996,Total,Asia/Pacific,0.466,0.343,8.176,3.468,60.984,2201.078,Low
25113,India,1997,Total,Asia/Pacific,0.471,0.349,8.210,3.637,61.388,2249.545,Low
25150,India,1998,Total,Asia/Pacific,0.478,0.356,8.242,3.806,61.792,2345.163,Low
25187,India,1999,Total,Asia/Pacific,0.486,0.362,8.274,3.975,62.207,2509.046,Low
25224,India,2000,Total,Asia/Pacific,0.491,0.369,8.306,4.144,62.669,2552.805,Low
25261,India,2001,Total,Asia/Pacific,0.496,0.372,8.337,4.221,63.091,2634.935,Low
25298,India,2002,Total,Asia/Pacific,0.503,0.380,8.528,4.298,63.616,2694.231,Low
25335,India,2003,Total,Asia/Pacific,0.516,0.399,9.122,4.375,64.094,2856.486,Low
25372,India,2004,Total,Asia/Pacific,0.525,0.409,9.386,4.452,64.524,3034.451,Low
25409,India,2005,Total,Asia/Pacific,0.534,0.419,9.650,4.529,64.996,3222.757,Low
25446,India,2006,Total,Asia/Pacific,0.543,0.430,9.915,4.637,65.412,3426.918,Low
25483,India,2007,Total,Asia/Pacific,0.553,0.441,10.179,4.744,65.788,3646.929,Medium
25520,India,2008,Total,Asia/Pacific,0.560,0.453,10.483,4.851,66.149,3698.176,Medium
25557,India,2009,Total,Asia/Pacific,0.565,0.455,10.419,4.958,66.513,3933.116,Medium
25594,India,2010,Total,Asia/Pacific,0.575,0.467,10.735,5.065,66.909,4189.433,Medium
25631,India,2011,Total,Asia/Pacific,0.588,0.490,11.294,5.302,67.359,4361.091,Medium
25668,India,2012,Total,Asia/Pacific,0.598,0.505,11.525,5.539,67.887,4529.016,Medium
25705,India,2013,Total,Asia/Pacific,0.607,0.513,11.541,5.776,68.460,4758.303,Medium
25742,India,2014,Total,Asia/Pacific,0.619,0.530,11.866,6.012,69.074,5056.666,Medium
25779,India,2015,Total,Asia/Pacific,0.629,0.540,11.947,6.249,69.636,5401.491,Medium
25816,India,2016,Total,Asia/Pacific,0.639,0.555,12.344,6.351,70.117,5732.914,Medium
25853,India,2017,Total,Asia/Pacific,0.644,0.553,12.163,6.452,70.467,6116.060,Medium
25890,India,2018,Total,Asia/Pacific,0.645,0.547,11.813,6.554,70.710,6449.186,Medium
25927,India,2019,Total,Asia/Pacific,0.645,0.540,11.464,6.655,70.910,6650.054,Medium
25964,India,2020,Total,Asia/Pacific,0.642,0.552,11.875,6.655,70.150,6107.494,Medium
26001,India,2021,Total,Asia/Pacific,0.633,0.552,11.875,6.655,67.240,6589.980,Medium

In [95]:
df[df["year"]==2021]

,country,year,region,continent,shdi,edindex,esch,msch,lifexp,gnic,hdi_category
26001,India,2021,Total,Asia/Pacific,0.633,0.552,11.875,6.655,67.24,6589.98,Medium

In [96]:
df[df['year']!=2021]['shdi']

24854    0.434
24891    0.437
24928    0.442
24965    0.446
25002    0.452
25039    0.458
25076    0.466
25113    0.471
25150    0.478
25187    0.486
25224    0.491
25261    0.496
25298    0.503
25335    0.516
25372    0.525
25409    0.534
25446    0.543
25483    0.553
25520    0.560
25557    0.565
25594    0.575
25631    0.588
25668    0.598
25705    0.607
25742    0.619
25779    0.629
25816    0.639
25853    0.644
25890    0.645
25927    0.645
25964    0.642
Name: shdi, dtype: float64

In [102]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, accuracy_score
from statsmodels.tsa.arima.model import ARIMA

features = df[['year', 'edindex','esch','msch','lifexp','gnic']]


train_size = int(len(df) * 0.8)
train, test = df[df["year"]!=2021], df[df["year"]==2021]

arima_model = ARIMA(train['shdi'], order=(5,1,0))
arima_fit = arima_model.fit()

arima_predictions = arima_fit.forecast(steps=len(test)+5)




X = features
y = df['shdi']

X_train, X_test, y_train, y_test = features[features["year"]!=2021] , features[features["year"]==2021] , df[df['year']!=2021]['shdi'],df[df['year']==2021]['shdi']

rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
print(f'Random Forest RMSE: {rf_rmse}')


categories = df['hdi_category']

X_class_train, X_class_test, y_class_train, y_class_test = train_test_split(X, categories, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_class_train, y_class_train)

class_predictions = rf_classifier.predict(X_class_test)

class_accuracy = accuracy_score(y_class_test, class_predictions)
print(f'Classification Accuracy: {class_accuracy}')

Random Forest RMSE: 0.000860000000000749
Classification Accuracy: 1.0

/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/Users/jeeva/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

In [103]:
arima_predictions

31    0.636466
32    0.629486
33    0.622241
34    0.614001
35    0.605092
36    0.596219
Name: predicted_mean, dtype: float64

In [104]:
train['shdi']

24854    0.434
24891    0.437
24928    0.442
24965    0.446
25002    0.452
25039    0.458
25076    0.466
25113    0.471
25150    0.478
25187    0.486
25224    0.491
25261    0.496
25298    0.503
25335    0.516
25372    0.525
25409    0.534
25446    0.543
25483    0.553
25520    0.560
25557    0.565
25594    0.575
25631    0.588
25668    0.598
25705    0.607
25742    0.619
25779    0.629
25816    0.639
25853    0.644
25890    0.645
25927    0.645
25964    0.642
Name: shdi, dtype: float64

In [91]:
X_train, X_test, y_train, y_test = features[features["year"]!=2021] , features[features["year"]==2021] , df[df['year']!=2021]['shdi'],df[df['year']==2021]['shdi']

rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
print(f'Random Forest RMSE: {rf_rmse}')

Random Forest RMSE: 0.007230586496341757

In [92]:
rf_predictions

array([0.62887, 0.60121, 0.56612, 0.75333, 0.63381, 0.70267, 0.71112,
       0.70579, 0.67203, 0.75827, 0.60729, 0.69109, 0.68319, 0.64079,
       0.70295, 0.67736, 0.60172, 0.6999 , 0.64865, 0.70417, 0.68854,
       0.62178, 0.60304, 0.74596, 0.66493, 0.62548, 0.6879 , 0.59178,
       0.61315, 0.65318, 0.75219, 0.61846, 0.72962, 0.66327, 0.71672,
       0.70624, 0.64182])

In [93]:
list(y_test)

[0.63,
 0.597,
 0.571,
 0.751,
 0.638,
 0.691,
 0.703,
 0.699,
 0.667,
 0.752,
 0.596,
 0.688,
 0.678,
 0.643,
 0.688,
 0.67,
 0.597,
 0.694,
 0.638,
 0.702,
 0.686,
 0.624,
 0.592,
 0.73,
 0.665,
 0.629,
 0.672,
 0.589,
 0.605,
 0.647,
 0.744,
 0.62,
 0.726,
 0.661,
 0.715,
 0.706,
 0.633]

In [77]:
class_predictions

array(['Medium', 'Medium', 'Medium', 'Low', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Medium', 'Low',
       'Low', 'Low', 'Low', 'Medium', 'Medium', 'Medium', 'High',
       'Medium', 'Medium', 'Low', 'Medium', 'Low', 'Medium', 'Medium',
       'Low', 'Low', 'Medium', 'Low', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Low', 'High', 'High',
       'Medium', 'Medium', 'High', 'Low', 'Medium', 'Medium', 'Medium',
       'Medium', 'Low', 'High', 'Low', 'Low', 'Medium', 'Low', 'High',
       'Medium', 'Low', 'High', 'Medium', 'Medium', 'Low', 'Medium',
       'Medium', 'Medium', 'Medium', 'High', 'Medium', 'Low', 'Medium',
       'Low', 'Medium', 'Low', 'Low', 'Low', 'Medium', 'Medium', 'Medium',
       'Medium', 'High', 'Low', 'Medium', 'Low', 'Low', 'High', 'Medium',
       'Medium', 'Medium', 'Medium', 'Low', 'High', 'Low', 'Low',
       'Medium', 'Medium', 'Medium', 'High', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Low', 'Low', 'Medium',
       'High', 'Low', 'Medium', 'Medium', 'Medium', 'Medium', 'Low',
       'Low', 'Medium', 'High', 'Medium', 'Medium', 'Low', 'Low',
       'Medium', 'Low', 'Medium', 'Medium', 'Medium', 'Low', 'Medium',
       'Medium', 'Low', 'High', 'Medium', 'Low', 'Medium', 'Medium',
       'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Low',
       'Low', 'Medium', 'Low', 'Medium', 'Medium', 'Medium', 'Low',
       'Medium', 'Medium', 'Low', 'High', 'Low', 'High', 'Medium',
       'Medium', 'High', 'Low', 'Low', 'Medium', 'Low', 'Low', 'Medium',
       'Medium', 'Medium', 'Medium', 'Low', 'Medium', 'Medium', 'Medium',
       'High', 'Medium', 'Low', 'Medium', 'Low', 'Medium', 'Low',
       'Medium', 'Medium', 'Medium', 'Low', 'Medium', 'Medium', 'Medium',
       'Low', 'High', 'High', 'High', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Low', 'Low', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'High', 'Low', 'Medium', 'Low', 'Medium',
       'Medium', 'Medium', 'Medium', 'High', 'Low', 'Medium', 'Medium',
       'Low', 'Low', 'Medium', 'Low', 'Medium', 'Medium', 'Low', 'Low',
       'Low', 'Medium', 'High', 'High', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'Low', 'Medium', 'High', 'Medium', 'Low',
       'Medium'], dtype=object)